const categories = {
  outcome: [
    "Transportation",
    "Subscriptions",
    "Memberships",
    "Housing",
    "Transfers",
    "Groceries",
    "Utilities",
    "Dining",
    "Entertainment",
    "Travel",
    "Healthcare",
    "Fashion",
    "Recreation",
    "Electronics",
    "Homeware",
    "Education",
    "Finance",
    "Pets",
    "Hobbies",
    "E-Commerce",
    "Services",
    "Eco",
    "Taxi",
    "Bars",
    "Clubs",
    "Fitness",
    "Beauty",
    "Books",
    "Games",
    "Gifts",
    "Music",
    "Sports",
    "Outdoor",
    "Other",
  ],
  income: [
    "Salary",
    "Deposits",
    "Transfers",
    "MobilePay",
    "Interest",
    "Dividends",
    "Gifts",
    "Rental Income",
    "Other",
  ],
};

module.exports = categories;
